export const OPEN_LOGIN_DIALOG = "OPEN_LOGIN_DIALOG";
export const CLOSE_LOGIN_DIALOG = "CLOSE_LOGIN_DIALOG";

export const OPEN_REGISTRATION_DIALOG = "OPEN_REGISTRATION_DIALOG";
export const CLOSE_REGISTRATION_DIALOG = "CLOSE_REGISTRATION_DIALOG";

export const UPDATE_LESSONS = 'UPDATE_LESSONS';
